In [34]:
import numpy as n

#zero Dimesion array[scalar]
zero_d= n.array([1])
zero_d

array([1])

In [35]:
#1d Array[Vector]
one_d=n.array([1,2,3])
one_d

array([1, 2, 3])

In [36]:
#2d Array[Matrices]
two_d=n.array([[1,2,3],[4,5,6]])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
import pandas as pd
name=["Cibi","Arun","Chris","Naveen"]
ct=pd.Series(name)
ct

0      Cibi
1      Arun
2     Chris
3    Naveen
dtype: object

In [38]:
three=n.array([1,2,3,4])
ct_1=pd.Series(three)
ct_1


0    1
1    2
2    3
3    4
dtype: int32

In [39]:
#lable Based indexing using pandas 
dt={"product A":1,"product b":2,"product c":3}
type(dt)
dt

{'product A': 1, 'product b': 2, 'product c': 3}

In [40]:
t=pd.Series(dt)
t

product A    1
product b    2
product c    3
dtype: int64

In [41]:
t["product A"]

1

In [42]:
#position based indexing using pandas 
p=pd.Series([36,69,96])
p

0    36
1    69
2    96
dtype: int64

In [43]:
#using index method to change index postion
p=pd.Series([36,69,96], index=[1,2,3])
p

1    36
2    69
3    96
dtype: int64

In [44]:
#Methods used in pandas 
#For Exmaple the data of the money that you have deposited in the bank:
m=pd.Series({"1/1/2022" : 12000,"2/2/2022" : 13000,"3/3/2022" : 15000,"4/4/2022": 16000,"5/5/2022": 18000,"6/6/2022":17000,"6/6/2023":18000,"7/8/2023":20000})
m

1/1/2022    12000
2/2/2022    13000
3/3/2022    15000
4/4/2022    16000
5/5/2022    18000
6/6/2022    17000
6/6/2023    18000
7/8/2023    20000
dtype: int64

In [45]:
m.sum() #here sum method sums the total money that you have deposited  

129000

In [46]:
m.max()#here max method shows the maximum amount that you have deposited in the bank  

20000

In [47]:
m.min()#here min method shows the minimum amount that you have deposited in the bank  

12000

In [48]:
m.idxmax() #here idx max method shows the maximum amount index is nothing here it is date ,that you have deposited in the bank  

'7/8/2023'

In [49]:
m.idxmin()#(#here it returns minimum value of the data's index)here idx min method shows the minimum amount index is nothing here it is date ,that you have deposited in the bank  

'1/1/2022'

In [50]:
m.head()# returns the first five data's of the data set 

1/1/2022    12000
2/2/2022    13000
3/3/2022    15000
4/4/2022    16000
5/5/2022    18000
dtype: int64

In [51]:
m.tail# returns the tail end of the data set 

<bound method NDFrame.tail of 1/1/2022    12000
2/2/2022    13000
3/3/2022    15000
4/4/2022    16000
5/5/2022    18000
6/6/2022    17000
6/6/2023    18000
7/8/2023    20000
dtype: int64>

In [52]:
m.head(3)  #we can use the Arguments  inside the parameters and it will be applied for both head and tail function 

1/1/2022    12000
2/2/2022    13000
3/3/2022    15000
dtype: int64

In [53]:
# Cerating data frames from scratch and Different way of creating data frames
#[to construct a Dictionary of Lists]
d={"Age":[22,33,44,55,66,77],"Gender":["M","M","F","F","M","F"]}
t=pd.DataFrame(d)
t

Age Gender
0   22      M
1   33      M
2   44      F
3   55      F
4   66      M
5   77      F

In [54]:
#Same data frame but With Label based indexing:
d={"Age":[22,33,44,55,66,77],"Gender":["M","M","F","F","M","F"]}
t=pd.DataFrame(d,index=["A","B","C","D","E","F"])
t

Age Gender
A   22      M
B   33      M
C   44      F
D   55      F
E   66      M
F   77      F

In [55]:
#To construct list of Dictionaries:
d=[{"Age":22,"Gender":"M"},
    {"Age":33,"Gender":"M"},
    {"Age":44,"Gender":"F"},
    {"Age":55,"Gender":"F"}, 
    {"Age":66,"Gender":"M"},
    {"Age":77,"Gender":"F"}]
alt=["A","B","C","D","E","F"]
t=pd.DataFrame(d,index=alt)
t

Age Gender
A   22      M
B   33      M
C   44      F
D   55      F
E   66      M
F   77      F

In [56]:
#zero based indexing with list of dict:
d=[{"Age":22,"Gender":"M"},
    {"Age":33,"Gender":"M"},
    {"Age":44,"Gender":"F"},
    {"Age":55,"Gender":"F"}, 
    {"Age":66,"Gender":"M"},
    {"Age":77,"Gender":"F"}]
t=pd.DataFrame(d,)
t

Age Gender
0   22      M
1   33      M
2   44      F
3   55      F
4   66      M
5   77      F

In [57]:
#Creating data frames with series of pandas:

d=pd.Series(["Cibi","Arun","Abi"])
t=pd.Series([23,25,21])
data ={"Name":d,"Age":t}
dd=pd.DataFrame(data)
dd


Name  Age
0  Cibi   23
1  Arun   25
2   Abi   21

In [58]:
#Using Index
d=pd.Series(["Cibi","Arun","Abi"],index=["A","B","C"])
t=pd.Series([23,25,21],index=["A","B","C"])
data ={"Name":d,"Age":t}
dd=pd.DataFrame(data)
dd


Name  Age
A  Cibi   23
B  Arun   25
C   Abi   21

In [59]:
#List of list
t=[["Cibi",22],["Arun",25],["Abi",21]]
df=pd.DataFrame(t)
df

0   1
0  Cibi  22
1  Arun  25
2   Abi  21

In [60]:
df.columns=["Name","Age"]
df

Name  Age
0  Cibi   22
1  Arun   25
2   Abi   21

In [61]:
#To construct a data frame in a Professional Way(data,column and Index)
df= pd.DataFrame(data=[["Cibi",22],["Arun",25],["Abi",21]],columns=["Name","Age"],index = ["A","B","C"])
df

Name  Age
A  Cibi   22
B  Arun   25
C   Abi   21

In [30]:
df.shape #Says how many rows and  Columns does your data frame or data sheet has  

(3, 2)

In [62]:
#To import the text file into python object File and open ,close and read function..Etc!

filename="source.csv"
filename

'source.csv'

In [65]:
file= open(filename,mode='r')
tt=file.read()
file.close()

In [66]:
file.closed

True

In [67]:
with open(filename,mode='r') as t:
    t.read()

In [68]:
#print(tt)

In [69]:
print(t)

<_io.TextIOWrapper name='source.csv' mode='r' encoding='cp1252'>


In [70]:
# To rewrite the content in the file :(proffesional way)
with open(filename,mode='w')as t:
    t.write("Hey Done and Dusted")
with open(filename,mode='r')as t:
    tt=t.read()
    print(tt)

Hey Done and Dusted


In [74]:
 #importing csv files through pandas by using read_csv file function:
    import pandas as pd  
pd.read_csv("student-por.csv")


school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        4   0  11  11  
1    ...      5        3      3     1     1      3        2   9  11  11  
2    ...      4        3      2     2     3      3        6  12  13  12  
3    ...      3        2      2     1     1      5        0  14  14  14  
4    ...      4        3      2     1     2      5        0  11  13  13  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
644  ...      5        4      2     1     2      5        4  10  11  10  
645  ...      4        3      4     1     1      1        4  15  15  16  
646  ...      1        1      1     1     1      5        6  11  12   9  
647  ...      2        4      5     3     4      2        6  10  10  10  
648  ...      4        4      1     3     4      5        4  10  11  11  

[649 rows x 33 columns]

In [76]:
#suppose if you have a raw dataset and big data set we can use this code to open and see what you want specifically 
filename="student-por.csv"
file_obj=read_csv(filename)
file_obj


school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        4   0  11  11  
1    ...      5        3      3     1     1      3        2   9  11  11  
2    ...      4        3      2     2     3      3        6  12  13  12  
3    ...      3        2      2     1     1      5        0  14  14  14  
4    ...      4        3      2     1     2      5        0  11  13  13  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
644  ...      5        4      2     1     2      5        4  10  11  10  
645  ...      4        3      4     1     1      1        4  15  15  16  
646  ...      1        1      1     1     1      5        6  11  12   9  
647  ...      2        4      5     3     4      2        6  10  10  10  
648  ...      4        4      1     3     4      5        4  10  11  11  

[649 rows x 33 columns]

In [82]:
#re-alocating the column we want as a index:
filename="student-por.csv"
file_obj=pd.read_csv(filename,index_col="Medu")
file_obj

school sex  age address famsize Pstatus  Fedu      Mjob      Fjob  \
Medu                                                                     
4        GP   F   18       U     GT3       A     4   at_home   teacher   
1        GP   F   17       U     GT3       T     1   at_home     other   
1        GP   F   15       U     LE3       T     1   at_home     other   
4        GP   F   15       U     GT3       T     2    health  services   
3        GP   F   16       U     GT3       T     3     other     other   
...     ...  ..  ...     ...     ...     ...   ...       ...       ...   
2        MS   F   19       R     GT3       T     3  services     other   
3        MS   F   18       U     LE3       T     1   teacher  services   
1        MS   F   18       U     GT3       T     1     other     other   
3        MS   M   17       U     LE3       T     1  services  services   
3        MS   M   18       R     LE3       T     2  services     other   

      reason  ... famrel  freetime  goout  Dalc Walc health absences  G1  G2  \
Medu          ...                                                              
4     course  ...      4         3      4     1    1      3        4   0  11   
1     course  ...      5         3      3     1    1      3        2   9  11   
1      other  ...      4         3      2     2    3      3        6  12  13   
4       home  ...      3         2      2     1    1      5        0  14  14   
3       home  ...      4         3      2     1    2      5        0  11  13   
...      ...  ...    ...       ...    ...   ...  ...    ...      ...  ..  ..   
2     course  ...      5         4      2     1    2      5        4  10  11   
3     course  ...      4         3      4     1    1      1        4  15  15   
1     course  ...      1         1      1     1    1      5        6  11  12   
3     course  ...      2         4      5     3    4      2        6  10  10   
3     course  ...      4         4      1     3    4      5        4  10  11   

      G3  
Medu      
4     11  
1     11  
1     12  
4     14  
3     13  
...   ..  
2     10  
3     16  
1      9  
3     10  
3     11  

[649 rows x 32 columns]

In [2]:
#importing data sets through numpy (loadtxt vs genfromtxt)
import numpy as n
t=n.genfromtxt("student-por.csv",delimiter=",")
t

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, 18., ...,  0., 11., 11.],
       [nan, nan, 17., ...,  9., 11., 11.],
       ...,
       [nan, nan, 18., ..., 11., 12.,  9.],
       [nan, nan, 17., ..., 10., 10., 10.],
       [nan, nan, 18., ..., 10., 11., 11.]])

In [3]:
f=n.loadtxt("student-por.csv",delimiter=",",dtype=n.str)
f

array([['school', 'sex', 'age', ..., 'G1', 'G2', 'G3'],
       ['GP', 'F', '18', ..., '0', '11', '11'],
       ['GP', 'F', '17', ..., '9', '11', '11'],
       ...,
       ['MS', 'F', '18', ..., '11', '12', '9'],
       ['MS', 'M', '17', ..., '10', '10', '10'],
       ['MS', 'M', '18', ..., '10', '11', '11']], dtype='<U10')

In [5]:
#partially cleaning the dataset while importing 
f=n.genfromtxt("student-por.csv",delimiter=",",skip_header=2)
f
#skip_header will remove the first two lines of data set

array([[nan, nan, 17., ...,  9., 11., 11.],
       [nan, nan, 15., ..., 12., 13., 12.],
       [nan, nan, 15., ..., 14., 14., 14.],
       ...,
       [nan, nan, 18., ..., 11., 12.,  9.],
       [nan, nan, 17., ..., 10., 10., 10.],
       [nan, nan, 18., ..., 10., 11., 11.]])

In [6]:
f=n.genfromtxt("student-por.csv",delimiter=",",skip_footer=2)
f
#skip_footer will remove the last two lines of data set and these functions are for rows 

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, 18., ...,  0., 11., 11.],
       [nan, nan, 17., ...,  9., 11., 11.],
       ...,
       [nan, nan, 19., ..., 10., 11., 10.],
       [nan, nan, 18., ..., 15., 15., 16.],
       [nan, nan, 18., ..., 11., 12.,  9.]])

In [10]:
#The intrested column that we want to use or selectively column amd its zero indexing based one!
f=n.genfromtxt("student-por.csv",delimiter=",",usecols=(1,2))
f

array([[nan, nan],
       [nan, 18.],
       [nan, 17.],
       ...,
       [nan, 18.],
       [nan, 17.],
       [nan, 18.]])

In [12]:
#all together in same process:
f=n.genfromtxt("student-por.csv",delimiter=",",skip_footer=2,usecols=(1,2),skip_header=2)
f

array([[nan, 17.],
       [nan, 15.],
       [nan, 15.],
       ...,
       [nan, 19.],
       [nan, 18.],
       [nan, 18.]])

In [1]:
#working with json files:
r='{"product a": 22,"product b": 33,"product c":44}'
r

'{"product a": 22,"product b": 33,"product c":44}'

In [2]:
type(r)

str

In [3]:
import json as j
t= j.loads(r)
t

{'product a': 22, 'product b': 33, 'product c': 44}

In [4]:
type(t)

dict

In [ ]:
#import json
#t=json.loads(var)
#h=pd.read_json(file.json)
#h
#to import data from excel spread sheet to python:
#f="var.csv"
#t=pd.read_excel(f)
#t